apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer-container
        image: producer_new:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER
          value: "kafka-broker:9092" 
        - name: TOPIC_NAME
          value: "stock-prices" 
