apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
  labels:
    app: sender
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: sender-container
        image: sender:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER
          value: "kafka-broker:9092" 
        - name: TOPIC_NAME
          value: "stock-prices" 
